spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    properties:
      # suppress "Method org.postgresql.jdbc.PgConnection.createClob() is not yet implemented."
      hibernate.temp.use_jdbc_metadata_defaults: false
    hibernate:
      ddl-auto: update
  profiles:
    active: dev
logging:
  level:
    # Enable hibernate query logging
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE