spring:
  datasource:
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      # suppress "Method org.postgresql.jdbc.PgConnection.createClob() is not yet implemented."
      hibernate.temp.use_jdbc_metadata_defaults: false
logging:
  level:
    # Enable hibernate query logging
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
